# Generated by Django 6.1.1 on 2026-09-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_moedas', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('skin', 'Skin de Avatar'), ('tema', 'Tema da Trilha'), ('vida', 'Recarga de Vidas')], default='skin', max_length=20)),
                ('icone_ou_imagem', models.ImageField(blank=True, null=True, upload_to='itens_loja/')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno (Jogador)'), ('professor', 'Professor (Criador)')], default='aluno', max_length=20)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('moedas', models.PositiveIntegerField(default=0)),
                ('vidas', models.PositiveIntegerField(default=5)),
                ('tema_fundo', models.CharField(choices=[('tema-padrao', 'Noite Estrelada'), ('tema-floresta', 'Trilha na Floresta'), ('tema-deserto', 'Deserto Escaldante'), ('tema-masmorra', 'Masmorra Sombria')], default='tema-padrao', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
                ('data_aquisicao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao.itemloja')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gamificacao.perfilusuario')),
            ],
            options={
                'unique_together': {('perfil', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.fase')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='gamificacao.perfilusuario')),
            ],
            options={
                'unique_together': {('perfil', 'fase')},
            },
        ),
    ]
