# Generated by Django 6.1.1 on 2026-09-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_alter_fase_unique_together_disciplina_tema_and_more'),
        ('gamificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questao_snapshot', models.TextField()),
                ('texto_opcao_snapshot', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TentativaFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_titulo_snapshot', models.CharField(max_length=150)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('total_questoes', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('aproveitamento', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de aproveitamento da tentativa.', max_digits=5)),
                ('aprovado', models.BooleanField(default=False)),
                ('xp_ganho', models.PositiveIntegerField(default=0)),
                ('moedas_ganhas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemcomprado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressofase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progressofase',
            name='data_ultima_tentativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressofase',
            name='melhor_aproveitamento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maior percentual obtido pelo aluno nesta fase.', max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='itemcomprado',
            constraint=models.UniqueConstraint(fields=('perfil', 'item'), name='unique_item_por_perfil'),
        ),
        migrations.AddConstraint(
            model_name='progressofase',
            constraint=models.UniqueConstraint(fields=('perfil', 'fase'), name='unique_progresso_por_perfil_fase'),
        ),
        migrations.AddField(
            model_name='respostatentativa',
            name='opcao_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_historicas', to='curriculo.opcao'),
        ),
        migrations.AddField(
            model_name='respostatentativa',
            name='questao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_historicas', to='curriculo.questao'),
        ),
        migrations.AddField(
            model_name='tentativafase',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas', to='curriculo.fase'),
        ),
        migrations.AddField(
            model_name='tentativafase',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_fase', to='gamificacao.perfilusuario'),
        ),
        migrations.AddField(
            model_name='respostatentativa',
            name='tentativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='gamificacao.tentativafase'),
        ),
        migrations.AddConstraint(
            model_name='respostatentativa',
            constraint=models.UniqueConstraint(fields=('tentativa', 'questao'), name='unique_questao_por_tentativa'),
        ),
    ]
