# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_respostatentativa_tentativafase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aparencia_interface',
            field=models.CharField(
                choices=[
                    ('sistema', 'Seguir preferência do sistema'),
                    ('claro', 'Modo claro'),
                    ('escuro', 'Modo escuro'),
                ],
                default='sistema',
                max_length=20,
            ),
        ),
    ]
