# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0003_perfilusuario_aparencia_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'desbloqueado',
                    models.BooleanField(default=False),
                ),
                (
                    'chave_disponivel',
                    models.BooleanField(default=False),
                ),
                (
                    'concluido',
                    models.BooleanField(default=False),
                ),
                (
                    'data_desbloqueio',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'data_conclusao',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'modulo',
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name='progressos_aluno',
                        to='curriculo.modulo',
                    ),
                ),
                (
                    'perfil',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='progressos_modulo',
                        to='gamificacao.perfilusuario',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('perfil', 'modulo'),
                        name='unique_progresso_por_perfil_modulo',
                    ),
                ],
            },
        ),
    ]
