# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'gamificacao',
            '0004_progressomodulo',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tema_fundo',
            field=models.CharField(
                choices=[
                    ('tema-padrao', 'Noite Estrelada'),
                    ('tema-floresta', 'Floresta Encantada'),
                    ('tema-deserto', 'Deserto Escaldante'),
                    ('tema-masmorra', 'Masmorra Sombria'),
                    ('tema-aurora', 'Aurora Boreal'),
                    ('tema-oceano', 'Oceano Profundo'),
                ],
                default='tema-padrao',
                max_length=50,
            ),
        ),
    ]
