# Generated by Django 6.1.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'gamificacao',
            '0005_alter_perfilusuario_tema_fundo',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressomodulo',
            name='chave_disponivel',
        ),
    ]
