# Generated by Django 6.0.3 on 2026-10-01 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0006_opcao_ordem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcao',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Marque quando o jogo estiver pronto para os alunos jogarem.'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='icone',
            field=models.CharField(default='book', help_text='Nome do ícone ou classe CSS', max_length=50),
        ),
        migrations.AlterField(
            model_name='fase',
            name='deslocamento_y',
            field=models.IntegerField(default=0, help_text='Deslocamento vertical em pixels (Ex: -60 sobe o botão, 80 desce).'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='explicacao_erro',
            field=models.TextField(blank=True, help_text='Feedback pedagógico exibido se o aluno errar a questão.'),
        ),
    ]
