# Generated by Django 6.1.1 on 2026-09-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Jogo/Trilha')),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='book', help_text='Nome do ícone ou classe CSS', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=False, help_text='Marque quando o jogo estiver pronto para os alunos jogarem.')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='curriculo.disciplina')),
            ],
            options={
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('teoria', 'Conteúdo Teórico'), ('quiz', 'Quiz / Exercícios'), ('desafio', 'Desafio de Recuperação')], default='quiz', max_length=20)),
                ('xp_recompensa', models.PositiveIntegerField(default=50)),
                ('moedas_recompensa', models.PositiveIntegerField(default=10)),
                ('deslocamento_y', models.IntegerField(default=0, help_text='Deslocamento vertical em pixels (Ex: -60 sobe o botão, 80 desce).')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='curriculo.modulo')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('modulo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('explicacao_erro', models.TextField(blank=True, help_text='Feedback pedagógico exibido se o aluno errar a questão.')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='curriculo.fase')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('e_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='curriculo.questao')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
    ]
