# Generated by Django 6.1.1 on 2026-09-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
