# Generated by Django 6.1.1 on 2026-09-18 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_disciplina_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tema',
            field=models.CharField(choices=[('tema-padrao', 'Noite Escura (Padrão)'), ('tema-floresta', 'Floresta Encantada'), ('tema-deserto', 'Deserto Escaldante'), ('tema-masmorra', 'Masmorra Sombria')], default='tema-padrao', max_length=30),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='icone',
            field=models.CharField(default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fase',
            name='deslocamento_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questao',
            name='explicacao_erro',
            field=models.TextField(blank=True),
        ),
    ]
