# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'curriculo',
            '0003_alter_fase_unique_together_disciplina_tema_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='tema',
            field=models.CharField(
                choices=[
                    ('tema-padrao', 'Noite Estrelada'),
                    ('tema-floresta', 'Floresta Encantada'),
                    ('tema-deserto', 'Deserto Escaldante'),
                    ('tema-masmorra', 'Masmorra Sombria'),
                    ('tema-aurora', 'Aurora Boreal'),
                    ('tema-oceano', 'Oceano Profundo'),
                ],
                default='tema-padrao',
                max_length=30,
            ),
        ),
    ]
