# Generated by Django 6.0.3 on 2026-10-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0007_alter_disciplina_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Marque quando o jogo estiver pronto para os alunos jogarem.'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='icone',
            field=models.CharField(default='book', help_text='Nome do ícone ou classe CSS', max_length=50),
        ),
        migrations.AlterField(
            model_name='fase',
            name='deslocamento_y',
            field=models.IntegerField(default=0, help_text='Deslocamento vertical em pixels (Ex: -60 sobe o botão, 80 desce).'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='explicacao_erro',
            field=models.TextField(blank=True, help_text='Feedback pedagógico exibido se o aluno errar a questão.'),
        ),
    ]
